=== Pradyumnabiswal99/FoundationTrainingDotNet/Day11/Break.dtd
<!ELEMENT Breaks (Break+)>
  <!--This is an DTD Comment-->
  <!ELEMENT Break (
	Time,
	(Duration|EndTime),
	(Snacks?)
)>
  <!ELEMENT Time (#PCDATA)>
  <!ELEMENT Duration (#PCDATA)>
  <!ELEMENT EndTime (#PCDATA)>
  <!ELEMENT Snacks (#PCDATA)>
  <!ATTLIST Break type (Morning|Evening|LateEvening) #REQUIRED>
<!ATTLIST Time ttype (AM|PM) "AM">

=== Pradyumnabiswal99/FoundationTrainingDotNet/Day11/Break.xml
<?xml version="1.0"  encoding="utf-8" standalone="yes"?>
<!DOCTYPE Breaks SYSTEM "Break.dtd">
<Breaks>
  <Break type="Morning">
    <Time>11:00</Time>
    <Duration>15Mins</Duration>
  </Break>
  <Break type="Evening">
    <Time ttype="PM">16:00</Time>
    <EndTime>16:15</EndTime>
    <Snacks>  Samosa &amp; Chutney</Snacks>
  </Break>
</Breaks>
